ci:
  autofix_prs: true
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autoupdate_schedule: weekly
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  skip: []
  submodules: false

repos:
  - repo: local
    hooks:
      - id: csharpier
        name: Run CSharpier on C# files
        entry: dotnet tool run CSharpier format
        language: system
        types:
          - c#
        description: CSharpier is an opinionated C# formatter inspired by Prettier.
